name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [
          { elixir: '1.14', otp: '23' },
          { elixir: '1.14', otp: '24' },
          { elixir: '1.14', otp: '25' },
          { elixir: '1.15', otp: '24' },
          { elixir: '1.15', otp: '25' },
          { elixir: '1.15', otp: '26' },
          { elixir: '1.16', otp: '24' },
          { elixir: '1.16', otp: '25' },
          { elixir: '1.16', otp: '26' },
          { elixir: '1.17', otp: '25' },
          { elixir: '1.17', otp: '26' },
          { elixir: '1.17', otp: '27' }
        ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.version.otp }}
        elixir-version: ${{ matrix.version.elixir }}
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-otp-${{ matrix.version.otp }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-otp-${{ matrix.version.otp }}-mix-
    - name: Install dependencies
      run: mix do deps.get, deps.compile
    - name: Run tests
      run: mix test --cover
    - uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: elixir-${{ matrix.version.elixir }},otp-${{ matrix.version.otp }}
